### ISSUE TITLE
Screen resize triggers session suspension

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#91]
From X2Go BTS:
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=829

Package: nx-x11-common
Version: 3.5.0.32-0x2go1~git20150317.672+jessie.heuler.1

Reproducable with every client and server so far from stable and heuler.
Only affects full sessions - users are not affected if running directly
an APPLICATION.

Pressing CTRL+ALT+R triggers error message in session.log of user,
resizes the screen but also triggers suspension of the session (note the
the Proxy-Warning does not occur every time):
Session: Resuming session at 'Thu Mar 26 11:11:56 2015'.
Info: Proxy running in server mode with pid '18054'.
Info: Waiting for connection from 'localhost' on port '30076'.
Info: Accepted connection from '127.0.0.1'.
Info: Connection with remote proxy completed.
Info: Using LAN link parameters 1536/24/1/0.
Info: Using agent parameters 5000/0/50/0/0.
Info: Using pack method '16m-jpeg-9' with session 'unix-kde-depth_24'.
Info: Not using NX delta compression.
Info: Not using ZLIB data compression.
Info: Not using ZLIB stream compression.
Info: Not using a persistent cache.
Info: Listening to X11 connections on display ':75'.
Info: Established X client connection.
Info: Using shared memory parameters 1/1/0/0K.
Info: Using local device configuration changes.
keyboard file created
Session: Session resumed at 'Thu Mar 26 11:12:03 2015'.
Info: Screen [0] resized to geometry [3840x1080] fullscreen [1].
<<-------- note from me: pressing ctrl+alt+r --------->>
Info: Disabled desktop resize mode in agent.
Session: Suspending session at 'Thu Mar 26 11:12:14 2015'.
Proxy: WARNING! Handling data for finishing FD#5 channel ID#1.
 suspended at 'Thu Mar 26 11:12:14 2015'.

Unfortunately we think this leads to another problem. Sometimes users
get suspended right after resuming their session:

Session: Session resumed at 'Wed Mar 25 21:30:37 2015'.
Info: Screen [0] resized to geometry [1680x1050] fullscreen [1].
Session: Suspending session at 'Wed Mar 25 21:30:39 2015'.

And last but not least this results in another problem - the screen does
not get resized correctly sometimes and is just shown as viewport.

**Comment by sunweaver** [comment]
As Ionic stated in IRC adding -nopersistent to x2goagent.options stops
the shortkey ctrl+alt+r from suspending the session after switching the
resize-mode

But by adding this option i am no longer able to suspend my session even
with the 'x2gosuspend-session'-command

**Comment by HolySephi** [comment]
I can confirm that this bug is still present in the current nightly ubuntu packages from:

deb http://packages.arctica-project.org/ubuntu-nightly trusty main

but only while connecting with x2goclient - neither a manually 'nxagent :1' nor 'x2goagent :1' shows this behaviour - they complain about the missong /usr/NX/bin/nxclient binary on pressing 'ctrl+alt+r'

**Comment by uli42** [comment]
In Events.c I can find this:

```
  if (nxagentOption(DesktopResize) == 0)
  {
    fprintf(stderr,"Info: Disabled desktop resize mode in agent.\n");

    nxagentLaunchDialog(DIALOG_DISABLE_DESKTOP_RESIZE_MODE);

    if (nxagentOption(Fullscreen) == 0)
    {
      sizeHints.max_width = nxagentOption(RootWidth);
      sizeHints.max_height = nxagentOption(RootHeight);

      XSetWMNormalHints(nxagentDisplay, nxagentDefaultWindows[pScreen->myNum],
                            &sizeHints);
    }
  }
  else
...
```

This indicated there should be a dialog. Dialogs are shown using /usr/NX/bin/nxclient which is not installed on most systems (binary from nomachine). Does it work when you link this to `/bin/true` or `/bin/false` (please try both)?

Also, is this limited to reconnected sessions? Does it also happen on new sessions?

Update: fixed double paste in code above

**Comment by HolySephi** [comment]
>  Does it work when you link this to or (please try both)?

Link to what?

**Comment by uli42** [comment]
Oh, wrong markup. I have fixed the above comment now. But for clarity:

```
mkdir -p /usr/NX/bin
ln -s /bin/true /usr/NX/bin/nxclient
```

**Comment by HolySephi** [comment]
neither linking /bin/true nor /bin/false changes the behaviour - whenever you are connected to a x2gosession or start a new one pressing ctrl+alt+r disconnects you beside turning resizing on or off

**Comment by uli42** [comment]
I think I have found the reason for this. The x2goagent that is started by the x2goserver sets the environment. In that environment I find

```
NX_CLIENT=/usr/lib/x2go/x2gosuspend-agent
```

`/usr/lib/x2go/x2gosuspend-agent` is a command that will trigger session suspension. However, NX_CLIENT is the variable that is used by nxcomp to find the nxclient executable which is used for displaying dialogs (the name is misleading, but that's the way it works). Well, and pressing CTRL-ALT-R triggers a dialog being displayed, so that the executable defined in $NX_CLIENT gets called. It will not display a dialog but suspend instead. If you remove/comment the line `system("x2gosuspend-session @words[2] > /dev/null");` in `/usr/lib/x2go/x2gosuspend-agent` the suspension no longer happens.

It seems that setting $NX_CLIENT is done in `/usr/bin/x2gostartagent`, and looking at the history it has been like this for more than 5 years (already contained in the first git commit). I have no idea why that has been done.

So I guess we can assume nobody is using this feature... And I am wondering if anybody ever used any functions that normally would display a dialog at all.

The nxclient executable should be able to handle at least these parameters:

```
--display

  Specify the X11 display where the client must connect. The option
  is only useful on platforms where the client is using the X-Window
  protocol for the display.

--dialog TYPE [--caption TITLE] [--message MESSAGE] [--local]
              [--window ID] [--class {info|warning|error}]
              [--allowmultiple]

  Show a dialog box. The option must be followed by a 'type' parame-
  ter which specifies the type of dialog.

  TYPE can be either:

  yesno
  ok
  error
  panic
  quit
  pulldown

  The user should specify a caption and a message to be shown. The
  option --local can be used to specify the proxy mode.

  The 'pulldown' dialog is a special tiny window that is embedded in
  the window specified in the --window parameter, to allow the user
  to suspend or terminate a session running in seamless mode.

  The --class option specifies the class of the message. When no class
  is specified the message will be assumed to be of the class 'Info'. 

  The --allowmultiple option specifies the possibility to launch more
  than one dialog with the same message.
```

**Comment by HristoMohamed** [comment]
Yep, this bug has attacked our infrastructure as well.
Commenting system("x2gosuspend-session @words[2] > /dev/null"); doesn't do the trick either.

I tried to hack stuff around and I tried commenting any lines concerned with session suspension from the x2gostartagent and x2goresume-session , but it still gets suspended, wait, what?

**Comment by HristoMohamed** [comment]
@uli42 
Hey, just a simple update:
I dont really think that  **/usr/lib64/x2go/x2gosuspend-agent** get executed at all when this bug gets triggered.

**Comment by uli42** [comment]
Hmm, you can check if your configuration has NX_CLIENT set. Find the PID of the x2goagent process on the server. Then do `strings /proc/<PID>/environ | grep NX_CLIENT`. The executable configured there will be executed when you press CTRL+ALT+r.

Maybe you have ANOTHER bug. To ensure we are talking about the same please write down the exact steps how to reproduce this.

**Comment by HristoMohamed** [comment]
Hey,
No I have the correct NX_CLIENT set there. 
**NX_CLIENT=/usr/lib64/x2go/x2gosuspend-agent**

I have tried a few times to change NX_CLIENT to /bin/true (like suggested above), sadly this does not help the issue.
I did a very dummy debug of this script, I have added a simple print on the perl script in a file:
I do not see that print appearing when my session gets autosuspended or when I press ctrl+alt+r.
However if I do try to execute manually the script, it does append it (albeit dies at some point due to missing parameters which is normal)
This brings me to the conclusion that it does not get triggered.

How I reproduce it:
1. Login and successfully start a x2go session with KDE/XFCE
2. Suspend my session
3. Try to relogin in the suspeded session
Most of the times I get autosuspended.
A few (lets say once in 5-6 attemts) in does login me successfully. CTRL+ALT+R suspends my session.
This I reproduce starting the client both from Windows and from Scientific Linux CERN 6.7. 
I am running x2go server version 4.0.1.19-3.

**Comment by uli42** [comment]
How do you supend the session in step 2?

Where are you looking for the debug print you inserted? You should find a log on the server in /home/$USER/.nx/<your session>/ (I cannot check for details right now)

**Comment by HristoMohamed** [comment]
Hey,
I suspend by clicking on the "SUSPEND" on the main client, (next to it is the terminate ;)) /I do not run it in fullscreen/.
I just do for the print, a simple system call /before you ask, yes it can write in /tmp/ / : 
**system("echo whatever > /tmp/whatever") ;**

Anyway from the logs I see (here I presset ctrl+alt+r, in another session it would just do it immediatelly with 20-30seconds in between):
Session: Session resumed at 'Thu Jul 21 10:45:23 2016'.
Info: Screen [0] resized to geometry [799x600] fullscreen [0].
Info: Screen [0] resized to geometry [800x600] fullscreen [0].
Session: Suspending session at 'Thu Jul 21 10:49:04 2016'.
Info: Waiting the cleanup timeout to complete.
Session: Session suspended at 'Thu Jul 21 10:49:05 2016'.

**Comment by uli42** [comment]
Hmm, I will try to resproduce this this evening (probably without windows being involved).

Can anybody else reproduce this?

**Comment by HristoMohamed** [comment]
Any update on this?
I am sure something is calling the /usr/bin/x2gosuspend-sesison => I moved it to a different file name and I could resume (albeit not suspend ;-) ) all my suspended test sessions.
It it funny because this bug with the auto-suspend only happens with sessions that have already been suspended, not with new sessions ;(

**Comment by uli42** [comment]
Sorry, forgot to update the topic. I can not provoke that behaviour. 

You could try to replace/extend `/usr/bin/x2gosuspend-session` by some code that dumps the process tree so we know where it is called from. E.g call `ps -axjf` right at the beginning.

**Comment by HristoMohamed** [comment]
Thanks a lot.
I am thinking that this is somehow related to x2goclean sessions. :(  

```
  1 30766 30607 19297 pts/28   19514 S        0   0:53 /usr/bin/perl /usr/sbin/x2gocleansessions
30766 27418 30607 19297 pts/28   19514 S        0   0:00  \_ su hrmohame -s /bin/sh -c x2gosuspend-session hrmohame-70-1470059598_stDKDE_dp24
27418 27419 27419 27419 ?           -1 Ss   10612   0:00      \_ /bin/bash /usr/bin/x2gosuspend-session hrmohame-70-1470059598_stDKDE_dp24
27419 27673 27419 27419 ?           -1 S    10612   0:00          \_ /bin/bash /usr/bin/x2gofeature X2GO_RUN_EXTENSIONS
    1 13248 13224  6720 pts/47    7961 S        0   0:48 /usr/bin/perl /usr/sbin/x2gocleansessions
13248 27696 13224  6720 pts/47    7961 S        0   0:00  \_ su hrmohame -s /bin/sh -c x2gosuspend-session hrmohame-70-1470059598_stDKDE_dp24
27696 27699 27699 27699 ?           -1 Ss   10612   0:00      \_ /bin/bash /usr/bin/x2gosuspend-session hrmohame-70-1470059598_stDKDE_dp24
27699 27702 27699 27699 ?           -1 R    10612   0:00          \_ ps -axjf
    1 13614 13602  6720 pts/47    7961 S        0   0:48 /usr/bin/perl /usr/sbin/x2gocleansessions --help
13614 27657 13602  6720 pts/47    7961 S        0   0:00  \_ su hrmohame -s /bin/sh -c x2gosuspend-session hrmohame-70-1470059598_stDKDE_dp24
27657 27661 27661 27661 ?           -1 Ss   10612   0:00      \_ /bin/bash /usr/bin/x2gosuspend-session hrmohame-70-1470059598_stDKDE_dp24
27661 27703 27661 27661 ?           -1 R    10612   0:00          \_ /usr/bin/perl /usr/lib64/x2go/x2gogetagent hrmohame-70-1470059598_stDKDE_dp24

```

**Comment by uli42** [comment]
I have looked into `/usr/sbin/x2gocleansessions`. There's only one code path that leads to x2gosuspend-session being called. That is when `/usr/lib/x2go/x2golistsessions_sql `hostname`` prints `S` in column 4 (starting from 0) but the session is still running. Then, and only then the session will get suspended by calling `x2gosuspend-session`. 

All this should be visible in the syslog once you activate debugging output in `/etc/x2go/x2goserver.conf`. Can you please post the relevant lines from the syslog?

In your listing above I can see you called `/usr/sbin/x2gocleansessions --help` which also seems to trigger the suspension. Here on my system it simply prints the message "unknown option help", but also does not exit (which I have reported as an x2go bug). So please try to kill process 13614 and see if the problem goes away.

**Comment by HristoMohamed** [comment]
It seems to have stopped after killing of all processes that had --help (three of them!), so I can't really reproduce this at the moment.
I tried around 10 reconnects and suspensions and it was ok, so I will ask my users to test it out as well.
I will report of it happens again.

Thanks a lot!

**Comment by uli42** [comment]
So as this seem solved _and_ is a x2go bug I'll close it for now.

**Comment by sunweaver** [comment]
Hi Uli,

On Tue Feb 28 21:45:06 2017 GMT+0100, Ulrich Sibiller wrote:
> So as this seem solved and is a x2go bug I'll close it for now. 

Actually I have been playing with the thought of providing an NX'ish dispatcher for those NXCLIENT command callbacks. The current implementation still expects a binary named nxclient to be around.

A dispatcher could then be something that generic solutions around NX could place there hooks into. I am thinking of some run-parts like executable...

**Comment by cavrinceanu** [comment]
Hi, I seem to still encounter this issue on the X2Go v.4.1.2.2. 
It worked just fine until suddenly dropped today. I thought it is a connection issue, but then each time I connect to the VM, screen size is reduced for GUI and instead huge window appears. Each resize of the window triggers a session suspension. 

Currently using X2Go on Windows 10 Pro to access to a Ubuntu 18.04 VM with MATE on it. 
No updates were made in between previous and current behavior..

**Comment by uli42** [comment]
Yes, the patch is waiting to be included for some time now. Don't know
why it is not being merged...

You can fix it yourself on your system by patching /usr/bin/x2gostartagent:

Change

export NX_CLIENT="${X2GO_LIB_PATH}/x2gosuspend-agent"

to

export NX_CLIENT="/usr/bin/nxdialog" (install the nxdialog package first)

It should also work to install x2goclient on the server and change above line to

export NX_CLIENT="/usr/bin/x2goclient"

HTH

Uli

**Comment by sunweaver** [comment]
Hi Uli,

Am Dienstag, 27. Juli 2021 schrieb Ulrich Sibiller:
> Yes, the patch is waiting to be included for some time now. Don't know
> why it is not being merged...
> 
> You can fix it yourself on your system by patching /usr/bin/x2gostartagent:
> 
> Change
> 
> export NX_CLIENT="${X2GO_LIB_PATH}/x2gosuspend-agent"
> 
> to
> 
> export NX_CLIENT="/usr/bin/nxdialog" (install the nxdialog package first)
> 
> It should also work to install x2goclient on the server and change above line to
> 
> export NX_CLIENT="/usr/bin/x2goclient"
> 
> HTH
> 
> Uli

Please point me to the patch. Thanks!

Mike

 
> 
> On Tue, Jul 27, 2021 at 9:05 PM Cristina Vrinceanu
> ***@***.***> wrote:
> >
> > Hi, I seem to still encounter this issue on the X2Go v.4.1.2.2.
> > It worked just fine until suddenly dropped today. I thought it is a connection issue, but then each time I connect to the VM, screen size is reduced for GUI and instead huge window appears. Each resize of the window triggers a session suspension.
> >
> > Currently using X2Go on Windows. Access to a Ubuntu 18.04 VM with MATE on it.
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ArcticaProject/nx-libs/issues/91#issuecomment-88780237

-- 
Gesendet von meinem Sailfish Gerät

**Comment by uli42** [comment]
https://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1540

**Comment by cavrinceanu** [comment]
> 
> 
> neither linking /bin/true nor /bin/false changes the behaviour - whenever you are connected to a x2gosession or start a new one pressing ctrl+alt+r disconnects you beside turning resizing on or off

Hi @uli42, thanks for the reply. In the meantime I've tried this and now it seems that is returned to normal. Not sure if it was temporary or not.

**Comment by uli42** [comment]
Worth mentioning: this will only work for NEW sessions. Already running
sessions will still know the old value of NX_CLIENT and therefore will call
x2gosuspend-agent
